### ISSUE TITLE
SpeechSplit actually better than AutoPST for seen speakers?

### ISSUE THREAD

**Issue by skol101** [auspicious3000/AutoPST#15]
Hello, I'm reading D.6. SPEECHSPLIT Baseline in the paper. 

Am I understanding this correctly that SpeechSplit performs better for rythm transfer when the doing conversation to a seen speaker ?

**Comment by auspicious3000** [comment]
No, this is not correct. SpeechSplit performs better only when it has the ground truth rhythm.
