### ISSUE TITLE
Missing basic execution with different set of speakers.

### ISSUE THREAD

**Issue by sainishalini** [auspicious3000/AutoPST#16]
Hi there,
I am trying to follow the code with my own dataset and could run Main_1.py and main_2.py to get xxx-A.ckpt and xxx-B.ckpt files.
Now I am not able to understand to run the demo file to prepare specific speakers dictionary to create and convert. Any help is appreciated with a little more direction to follow the steps.

**Comment by auspicious3000** [comment]
What matters is the model's required inputs. The model requires source cepstrum, source cepstrum lengths, masks made from source ceptrum lengths, and target speaker embedding. That's what the dictionary provides. You don't need to use a dictionary as long as you have the required inputs.

**Comment by sainishalini** [comment]
Thanks! I think, I may be missing something basic. Not cleat on what to do next after training the model?
How to create or define the sources speakers and target speakers? how to get the converted samples? Thanks for your help!

**Comment by auspicious3000** [comment]
You are welcome. For the basics, please refer to the paper. https://arxiv.org/abs/2106.08519

**Comment by sainishalini** [comment]
thanks, let me check again. I was hoping to get more straight forward direction and commands to run the code for the conversion by providing any set of source and target speakers through command line or modifying the demo code. Got lost on it after training the model.
