### ISSUE TITLE
Issue with stop prediction for longer utterances.

### ISSUE THREAD

**Issue by bshall** [auspicious3000/AutoPST#19]
Hi @auspicious3000,

First, thanks for releasing this repository! I've been trying to compare AutoPST to some upcoming work but I'm having an issue with the stop token prediction when converting utterances longer than 1 or 2 seconds. I noticed that you clipped some of the VCTK files for your demo page (and in the test dictionary you provided) so that they're much shorter. How did you use the test utterances in your evaluations? Do you have any recommendations so that I can make as fair a comparison as possible.

Thanks,
Benjamin

**Comment by auspicious3000** [comment]
Hi,

We use the test sentences from AutoVC and SpeechSplit. The original utterances of VCTK may contain several sentences in a single utterance. To make each test utterance a single sentence, we split the long utterances into single sentences.
