### ISSUE TITLE
test_vctk.meta

### ISSUE THREAD

**Issue by ZimingY** [auspicious3000/AutoPST#2]
Hi,

I am wondering how the "test_vctk.meta"  is created in the demo file?

Thanks!

**Comment by auspicious3000** [comment]
Just put the cepstrum and speaker embedding into a list.

**Comment by ZimingY** [comment]
Thanks! By speaker embedding, I guess you mean the one hot representation? And does it indicate that the speaker that we "transfers to" need to be seen in the training data? 
One more question, is the output quality restricted by the input length ? The demo audios are all like 1s~2s. How does it performs on 5s~10s audios?

**Comment by auspicious3000** [comment]
Yes.

No.

**Comment by ZimingY** [comment]
> Just put the cepstrum and speaker embedding into a list.

Hi, is cepstrum computed by one of these three in [prepare_train_data.py]? If so can you point
 me which one is it? If not, are there any codes in the github reflect this computation? 
(https://github.com/auspicious3000/AutoPST/blob/main/prepare_train_data.py)
`        np.save(os.path.join(targetDir_cd, subdir, fileName[:-4]), 
                codes.cpu().numpy(), allow_pickle=False)
        np.save(os.path.join(targetDir_sp, subdir, fileName[:-4]), 
                S.astype(np.float32), allow_pickle=False)
        np.save(os.path.join(targetDir_cep, subdir, fileName[:-4]), 
                cc_norm.astype(np.float32), allow_pickle=False)`

**Comment by auspicious3000** [comment]
cep stands for cepstrum
