### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by avanitanna** [auspicious3000/AutoPST#20]
@auspicious3000 We tried reproducing results using your codebase and the dataset found here https://datashare.ed.ac.uk/handle/10283/3443 (that you use) but unfortunately, we were unable to. The outputs that we have so far are extremely noisy (even if source and target speakers are the same). Could you please share a working code with us that might help us reproduce the results? I would greatly appreciate your inputs!

**Comment by auspicious3000** [comment]
We got many feedbacks from users that they are able to reproduce the results using this code. It might be possible there are inconsistencies when using the code. It might be helpful to read the code and paper in greater detail.
