### ISSUE TITLE
How to test AutoPST in onother languages?

### ISSUE THREAD

**Issue by zelenooki87** [auspicious3000/AutoPST#3]
I have not success to test final section of vocoder code in autopst. In conda envionment, all dependencies have installed.
Error something like"from synthessis cannot import build_model" allways shows.
I want to ask you, do I need to train in AutoVC speakers, cause I want to use for my own sounds, in another language, not English?

just want to clone voice of one recording to onother. for different speakers. 
Do these recordings need to be same lenght and same sentences spoken to be compared during training?

BTW, I have RTX3060, and this card not supported by version of 1.6.0 of pytorch. I have installed fist onmt python package, than pytorch 1.7.0 with Cuda 11
Thank you

**Comment by zelenooki87** [comment]
***update

I copied .py files from autovc to autopst folder... and then demo worked.
tried to install tensorflow gpu and onmt-tf and newest pytorch and error occured in training-----something about numpy array and negatives values....and tried older versions of numpy like 1.16.4.....etc
to developers, have you check your code?

**Comment by auspicious3000** [comment]
You don't need tensorflow gpu, onmt-tf, etc   
For another language, you need to retrain the model. This model is trained on English only.

**Comment by zelenooki87** [comment]
To be preceise I want recreate same voice style, of singing rap vocal. is this repository best bet to do this?

**Comment by auspicious3000** [comment]
That will be challenging.

**Comment by zelenooki87** [comment]
so, do you think worth trying? is possible? I already have recorded rap vocals with different speakers, so this is not problem.

**Comment by auspicious3000** [comment]
Probably not.
